services:
  - type: web
    name: kopis-performance
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT main:app
    healthCheckPath: /ping
    healthCheckTimeout: 180
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16 