services:
  - type: web
    name: kopis-performance
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        value: 8000
    buildFilter:
      paths:
        - requirements.txt
        - main.py
        - templates/**
        - static/** 